k3s_version: v1.32.3+k3s1
k3s_config_file: /etc/rancher/k3s/config.yaml
k3s_service_file: /etc/systemd/system/k3s.service
k3s_server_config:
  secrets-encryption: true
  # disable:
  #   - traefik
  # disable-helm-controller: true
